-- HASWOLF V5 ULTIMATE FOUNDATION
alter table public.products
 add column if not exists favorite_count bigint not null default 0,
 add column if not exists is_daily_favorite boolean not null default false,
 add column if not exists is_best_price boolean not null default false,
 add column if not exists low_stock_alert boolean not null default false;

alter table public.profiles
 add column if not exists premium_tier text not null default 'normal',
 add column if not exists premium_until timestamptz,
 add column if not exists last_seen_at timestamptz;

create table if not exists public.guilds(
 id uuid primary key default gen_random_uuid(), name text unique not null, badge text default '🛡',
 color text default '#d9aa4a', owner_id uuid references auth.users(id), is_active boolean default true,
 created_at timestamptz default now()
);
create table if not exists public.guild_members(
 id bigint generated by default as identity primary key, guild_id uuid references public.guilds(id) on delete cascade,
 user_id uuid references auth.users(id) on delete cascade, role text default 'member', status text default 'active',
 created_at timestamptz default now(), unique(guild_id,user_id)
);
create table if not exists public.guild_invites(
 id uuid primary key default gen_random_uuid(), guild_id uuid references public.guilds(id) on delete cascade,
 inviter_id uuid references auth.users(id), invited_user_id uuid references auth.users(id),
 status text default 'pending', expires_at timestamptz, created_at timestamptz default now()
);
alter table public.chat_rooms
 add column if not exists slow_mode_seconds integer not null default 0,
 add column if not exists can_read_roles text[] not null default array['member','moderator','manager','founder'],
 add column if not exists can_write_roles text[] not null default array['member','moderator','manager','founder'],
 add column if not exists can_voice_roles text[] not null default array['member','moderator','manager','founder'],
 add column if not exists can_screen_share_roles text[] not null default array['member','moderator','manager','founder'],
 add column if not exists pinned_message_id uuid;

create table if not exists public.moderation_queue(
 id bigint generated by default as identity primary key, user_id uuid references auth.users(id),
 content_type text not null, original_content text, masked_content text, reason text, risk_score numeric default 0,
 status text default 'pending', created_at timestamptz default now(), reviewed_at timestamptz, reviewed_by uuid references auth.users(id)
);
create table if not exists public.message_reports(
 id bigint generated by default as identity primary key, message_id uuid, reporter_id uuid references auth.users(id),
 reason text, status text default 'open', created_at timestamptz default now()
);
create table if not exists public.security_events(
 id bigint generated by default as identity primary key, user_id uuid references auth.users(id),
 event_type text not null, risk_level text default 'low', summary text, metadata jsonb default '{}'::jsonb,
 created_at timestamptz default now()
);
create table if not exists public.audit_logs(
 id bigint generated by default as identity primary key, admin_id uuid references auth.users(id),
 action text not null, entity_type text, entity_id text, summary text, metadata jsonb default '{}'::jsonb,
 created_at timestamptz default now()
);
create table if not exists public.campaigns(
 id bigint generated by default as identity primary key, title text not null, body text,
 campaign_type text not null default 'banner', target_audience text not null default 'all',
 desktop_image_url text, mobile_image_url text, link_url text, sound_enabled boolean default false,
 is_active boolean default false, starts_at timestamptz, ends_at timestamptz, created_by uuid references auth.users(id),
 created_at timestamptz default now()
);
create table if not exists public.site_notifications(
 id bigint generated by default as identity primary key, title text not null, body text,
 notification_type text not null default 'announcement', product_id bigint references public.products(id) on delete set null,
 sound_enabled boolean default false, is_active boolean default true, created_by uuid references auth.users(id),
 created_at timestamptz default now()
);

create or replace function public.sync_product_favorite_count()
returns trigger language plpgsql security definer set search_path=public as $$
begin
 if tg_op='INSERT' then update products set favorite_count=favorite_count+1 where id=new.product_id; return new;
 elsif tg_op='DELETE' then update products set favorite_count=greatest(0,favorite_count-1) where id=old.product_id; return old;
 end if; return null;
end $$;
drop trigger if exists product_favorite_count_trigger on public.product_favorites;
create trigger product_favorite_count_trigger after insert or delete on public.product_favorites
for each row execute function public.sync_product_favorite_count();

alter table public.guilds enable row level security;
alter table public.guild_members enable row level security;
alter table public.guild_invites enable row level security;
alter table public.moderation_queue enable row level security;
alter table public.message_reports enable row level security;
alter table public.security_events enable row level security;
alter table public.audit_logs enable row level security;
alter table public.campaigns enable row level security;
alter table public.site_notifications enable row level security;

create or replace function public.is_haswolf_admin()
returns boolean language sql stable security definer set search_path=public as $$
 select coalesce(auth.jwt()->>'email','')='haswolf666@gmail.com';
$$;
do $$ begin
 create policy "admin guilds" on public.guilds for all using(public.is_haswolf_admin()) with check(public.is_haswolf_admin());
exception when duplicate_object then null; end $$;
do $$ begin
 create policy "admin moderation" on public.moderation_queue for all using(public.is_haswolf_admin()) with check(public.is_haswolf_admin());
exception when duplicate_object then null; end $$;
do $$ begin
 create policy "admin security" on public.security_events for all using(public.is_haswolf_admin()) with check(public.is_haswolf_admin());
exception when duplicate_object then null; end $$;
do $$ begin
 create policy "admin audit" on public.audit_logs for all using(public.is_haswolf_admin()) with check(public.is_haswolf_admin());
exception when duplicate_object then null; end $$;
do $$ begin
 create policy "admin campaigns" on public.campaigns for all using(public.is_haswolf_admin()) with check(public.is_haswolf_admin());
exception when duplicate_object then null; end $$;
do $$ begin
 create policy "public active campaigns" on public.campaigns for select using(is_active=true);
exception when duplicate_object then null; end $$;
do $$ begin
 create policy "admin notifications" on public.site_notifications for all using(public.is_haswolf_admin()) with check(public.is_haswolf_admin());
exception when duplicate_object then null; end $$;
do $$ begin
 create policy "public active notifications" on public.site_notifications for select using(is_active=true);
exception when duplicate_object then null; end $$;
