"use client";
import {FormEvent,useEffect,useState} from "react";import AdminGuard from "../../../components/AdminGuard";import {supabase} from "../../../lib/supabase";
type Room={id:string;name:string;slug:string;kind:string;category:string;slow_mode_seconds:number;is_active:boolean};type UserRow={id:string;nickname:string|null;chat_banned_until?:string|null};
const slow=[0,5,10,15,30,60,120,300];
export default function Page(){const[rooms,setRooms]=useState<Room[]>([]);const[users,setUsers]=useState<UserRow[]>([]);const[menu,setMenu]=useState("");const[msg,setMsg]=useState("");const[form,setForm]=useState({name:"",slug:"",kind:"text",category:"chat"});
 async function load(){const[r,u]=await Promise.all([supabase.from("chat_rooms").select("id,name,slug,kind,category,slow_mode_seconds,is_active").order("name"),supabase.from("profiles").select("id,nickname,chat_banned_until").order("created_at",{ascending:false}).limit(80)]);if(r.error)setMsg(r.error.message);else setRooms((r.data||[]) as Room[]);if(!u.error)setUsers((u.data||[]) as UserRow[])}useEffect(()=>{void load()},[]);
 async function create(e:FormEvent){e.preventDefault();const{error}=await supabase.from("chat_rooms").insert({...form,slug:form.slug||form.name.toLocaleLowerCase("tr").replace(/[^a-z0-9]+/g,"-")});setMsg(error?.message||"Yeni oda oluşturuldu.");if(!error){setForm({name:"",slug:"",kind:"text",category:"chat"});await load()}}
 async function updateRoom(room:Room,patch:Partial<Room>){const{error}=await supabase.from("chat_rooms").update(patch).eq("id",room.id);setMsg(error?.message||"Oda ayarı güncellendi.");await load()}async function removeRoom(room:Room){if(!confirm(`${room.name} odası silinsin mi?`))return;await supabase.from("chat_rooms").delete().eq("id",room.id);await load()}
 async function ban(user:UserRow,minutes:number){const until=new Date(Date.now()+minutes*60000).toISOString();const{error}=await supabase.from("profiles").update({chat_banned_until:until}).eq("id",user.id);if(!error)await supabase.from("audit_logs").insert({action:"chat_ban",entity_type:"profile",entity_id:user.id,summary:`${user.nickname||user.id} ${minutes} dakika chat ban aldı`});setMsg(error?.message||`${user.nickname||"Kullanıcı"} ${minutes} dakika susturuldu.`);setMenu("");await load()}
 async function unban(user:UserRow){await supabase.from("profiles").update({chat_banned_until:null}).eq("id",user.id);setMenu("");await load()}
 return <AdminGuard title="Sohbet Yönetimi" subtitle="Oda oluştur, hızlı slow mode ayarla ve kullanıcı mahlasından tek tıkla moderasyon uygula."><form onSubmit={create} className="haswolf-admin-form-grid"><label><span>Oda adı</span><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label><span>Slug</span><input value={form.slug} onChange={e=>setForm({...form,slug:e.target.value})} placeholder="otomatik oluşur"/></label><label><span>Tür</span><select value={form.kind} onChange={e=>setForm({...form,kind:e.target.value})}><option value="text">Yazı</option><option value="voice">Ses</option></select></label><label><span>Kategori</span><select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option value="chat">Genel</option><option value="trade">Ticaret</option><option value="guild">Lonca</option><option value="support">Destek</option></select></label><button>＋ Oda Oluştur</button></form>{msg&&<p className="haswolf-admin-message">{msg}</p>}<div className="haswolf-admin-two-column"><section className="haswolf-admin-card"><header className="haswolf-admin-section-title"><div><small>ODA KOMUTLARI</small><h2>Aktif Odalar</h2></div><b>{rooms.length}</b></header><div className="haswolf-admin-room-list">{rooms.map(r=><article key={r.id}><div><strong>{r.kind==="voice"?"🔊":"#"} {r.name}</strong><small>{r.category} · {r.slug}</small></div><label><span>Yavaş mod</span><select value={r.slow_mode_seconds} onChange={e=>updateRoom(r,{slow_mode_seconds:Number(e.target.value)})}>{slow.map(v=><option value={v} key={v}>{v===0?"Kapalı":`${v} sn`}</option>)}</select></label><button onClick={()=>updateRoom(r,{is_active:!r.is_active})}>{r.is_active?"Kilitle":"Aç"}</button><button className="is-danger" onClick={()=>removeRoom(r)}>Sil</button></article>)}</div></section><section className="haswolf-admin-card"><header className="haswolf-admin-section-title"><div><small>HIZLI MODERASYON</small><h2>Kullanıcı Mahlasları</h2></div><b>{users.length}</b></header><div className="haswolf-admin-user-list">{users.map(u=><article key={u.id}><button className="haswolf-user-menu-trigger" onClick={()=>setMenu(menu===u.id?"":u.id)}><span>👤</span><span><b>{u.nickname||"İsimsiz"}</b><small>{u.chat_banned_until&&new Date(u.chat_banned_until)>new Date()?`Banlı · ${new Date(u.chat_banned_until).toLocaleTimeString("tr-TR")}`:"Aktif kullanıcı"}</small></span><i>⋮</i></button>{menu===u.id&&<div className="haswolf-user-quick-menu"><strong>Hızlı İşlemler</strong><button onClick={()=>ban(u,10)}>10 dk sustur</button><button onClick={()=>ban(u,30)}>30 dk sustur</button><button onClick={()=>ban(u,1440)}>24 saat banla</button><button onClick={()=>unban(u)}>Banı kaldır</button><a href={`/admin/kullanicilar?user=${u.id}`}>Profili incele</a></div>}</article>)}</div></section></div></AdminGuard>}
