"use client";
import { useEffect,useMemo,useState } from "react";
import AdminGuard from "../../../components/AdminGuard";
import { supabase } from "../../../lib/supabase";
import { FOUNDER_EMAIL } from "../../../lib/admin-access";
type Profile={id:string;nickname:string|null;created_at:string};
type Member={user_id:string;created_at:string;profiles?:{nickname:string|null}|null};
export default function Page(){
 const[profiles,setProfiles]=useState<Profile[]>([]),[members,setMembers]=useState<Member[]>([]),[q,setQ]=useState(""),[msg,setMsg]=useState(""),[busy,setBusy]=useState(""),[founder,setFounder]=useState(false);
 async function load(){const{data:{user}}=await supabase.auth.getUser();setFounder((user?.email||"").toLowerCase()===FOUNDER_EMAIL);const[p,m]=await Promise.all([supabase.from("profiles").select("id,nickname,created_at").order("created_at",{ascending:false}).limit(250),supabase.from("admin_members").select("user_id,created_at,profiles(nickname)").order("created_at")]);if(p.error)setMsg(p.error.message);else setProfiles((p.data||[]) as Profile[]);if(m.error)setMsg(m.error.message);else setMembers((m.data||[]) as unknown as Member[])}
 useEffect(()=>{void load()},[]);
 const memberIds=new Set(members.map(x=>x.user_id));const filtered=useMemo(()=>profiles.filter(x=>(x.nickname||x.id).toLowerCase().includes(q.toLowerCase())),[profiles,q]);
 async function grant(p:Profile){if(!founder)return setMsg("Yönetici üyeliğini yalnızca kurucu verebilir.");setBusy(p.id);setMsg("");const{error}=await supabase.from("admin_members").insert({user_id:p.id});setMsg(error?.message||`${p.nickname||"Hesap"} yönetici yapıldı.`);await load();setBusy("")}
 async function revoke(p:Profile){if(!founder)return setMsg("Yönetici üyeliğini yalnızca kurucu kaldırabilir.");setBusy(p.id);const{error}=await supabase.from("admin_members").delete().eq("user_id",p.id);setMsg(error?.message||"Yönetici üyeliği kaldırıldı.");await load();setBusy("")}
 return <AdminGuard title="Yönetici Üyelikleri" subtitle="Kurucu + en fazla 2 yönetici. Yöneticiler kod/depo erişimi dışında tüm panel yetkilerine sahiptir."><section className="haswolf-admin-toolbar"><div><b>♛ Yönetim Yetki Merkezi</b><small>{members.length}/2 yardımcı yönetici atanmış durumda.</small></div><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Mahlas veya kullanıcı ID ara"/></section>{msg&&<p className="haswolf-admin-message">{msg}</p>}<section className="haswolf-admin-card"><article className="haswolf-founder-card"><div><span>Kurucu</span><b>🔥 HASWOLF Kurucusu</b><small>{FOUNDER_EMAIL}</small></div><strong>DEĞİŞTİRİLEMEZ</strong></article><div className="haswolf-admin-responsive-list haswolf-admin-action-list">{filtered.map(p=><article key={p.id} className={memberIds.has(p.id)?"is-admin-member":""}><div><span>Hesap</span><b>{p.nickname||"İsimsiz hesap"}</b><small>{p.id}</small></div><div><span>Yetki</span><b>{memberIds.has(p.id)?"♛ Yönetici":"Normal üye"}</b><small>{memberIds.has(p.id)?"Tüm site yönetim yetkileri":"Yönetim erişimi yok"}</small></div><div className="haswolf-admin-actions"><span>Yönetici Üyeliği</span>{memberIds.has(p.id)?<button className="is-danger" disabled={!founder||busy===p.id} onClick={()=>revoke(p)}>Yetkiyi Kaldır</button>:<button disabled={!founder||busy===p.id||members.length>=2} onClick={()=>grant(p)}>Yönetici Yap</button>}</div></article>)}</div></section></AdminGuard>
}
