"use client";
import {useEffect,useState} from "react";import AdminGuard from "../../../components/AdminGuard";import {supabase} from "../../../lib/supabase";
type Row={id:string;nickname:string|null;premium_tier:string;premium_until:string|null;created_at:string};
const plans=[30,90,180,365,0];
export default function Page(){const[rows,setRows]=useState<Row[]>([]);const[busy,setBusy]=useState("");const[msg,setMsg]=useState("");const[q,setQ]=useState("");
 async function load(){const{data,error}=await supabase.from("profiles").select("id,nickname,premium_tier,premium_until,created_at").order("created_at",{ascending:false}).limit(250);if(error)setMsg(error.message);else setRows((data||[]) as Row[])}
 useEffect(()=>{void load();const c=supabase.channel("admin-premium-live").on("postgres_changes",{event:"*",schema:"public",table:"profiles"},()=>void load()).subscribe();return()=>{void supabase.removeChannel(c)}},[]);
 async function grant(row:Row,days:number){setBusy(row.id);setMsg("");const until=days===0?null:new Date(Date.now()+days*86400000).toISOString();const tier=days===0?"lifetime":"premium";const{error}=await supabase.from("profiles").update({premium_tier:tier,premium_until:until}).eq("id",row.id);if(error)setMsg(error.message);else{await supabase.from("audit_logs").insert({action:"premium_granted",entity_type:"profile",entity_id:row.id,summary:`${row.nickname||row.id} hesabına ${days||"süresiz"} Premium verildi`});setMsg("Premium üyelik başarıyla tanımlandı.");await load()}setBusy("")}
 async function revoke(row:Row){setBusy(row.id);const{error}=await supabase.from("profiles").update({premium_tier:"normal",premium_until:null}).eq("id",row.id);setMsg(error?.message||"Premium üyelik kaldırıldı.");await load();setBusy("")}
 const filtered=rows.filter(r=>(r.nickname||r.id).toLowerCase().includes(q.toLowerCase()));
 return <AdminGuard title="Premium Üyelikler" subtitle="Hesaba tek tıkla 30/90/180/365 günlük veya süresiz Premium tanımla."><section className="haswolf-admin-toolbar"><div><b>🔥 Premium Komuta Merkezi</b><small>Aktif üyelikler alevli profil ve özel avantajlar kazanır.</small></div><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Mahlas veya kullanıcı ID ara"/></section>{msg&&<p className="haswolf-admin-message">{msg}</p>}<section className="haswolf-admin-card"><div className="haswolf-admin-responsive-list haswolf-admin-action-list">{filtered.map(row=><article key={row.id} className={row.premium_tier!=="normal"?"is-premium":""}><div><span>Hesap</span><b>{row.nickname||"İsimsiz hesap"}</b><small>{row.id}</small></div><div><span>Durum</span><b>{row.premium_tier==="normal"?"Normal":`🔥 ${row.premium_tier.toUpperCase()}`}</b><small>{row.premium_until?new Date(row.premium_until).toLocaleString("tr-TR"):row.premium_tier!=="normal"?"Süresiz":"—"}</small></div><div className="haswolf-admin-actions"><span>Premium Üyelik Ver</span>{plans.map(d=><button disabled={busy===row.id} onClick={()=>grant(row,d)} key={d}>{d?`${d} Gün`:"Süresiz"}</button>)}<button className="is-danger" disabled={busy===row.id} onClick={()=>revoke(row)}>Kaldır</button></div></article>)}</div></section></AdminGuard>}
